services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-nginx-frontend
    ports:
      - "4000:80"  # map container's port 80 to host's port 4000
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_STRIPE_PUBLIC_KEY=${VUE_APP_STRIPE_PUBLIC_KEY}
    restart: unless-stopped